### ISSUE TITLE
공통 CSS 서식 추출

### ISSUE THREAD

**Issue by quack337** [quack337/bbs1#9]
다음 CSS 서식이 여러 뷰 파일에 중복된다.
```css
div.panel {
  margin: 1em;
  border: 1px solid #ddd; border-radius: 5px;
  box-shadow: 3px 3px 3px #ccc; }
div.panel h1 {
  margin: 0; font-size: 14pt; font-weight: bold; 
  background:linear-gradient(90deg, #def, #bcd); padding: 10px 15px 7px 15px; }
div.panel-body { padding: 20px; font-size: 11pt; }
```

이 부분을 common.css 파일에 추출하여 공유하자.
